import { createContext, useContext, useState, useEffect } from 'react';
import PropTypes from 'prop-types';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');
    const [translations] = useState({
        en: {
            // Navigation
            home: 'Home',
            dashboard: 'Dashboard',
            'Dashboard': 'Dashboard',
            'Meal Plan': 'Meal Plan',
            'Analytics': 'Analytics',
            'Achievements': 'Achievements',
            'Profile': 'Profile',
            profile: 'Profile',
            settings: 'Settings',
            'Subscription': 'Subscription',
            logout: 'Logout',
            login: 'Login',
            register: 'Register',

            // Tab Bar Navigation
            mealPlan: 'Meal Plan',
            analytics: 'Analytics',
            achievements: 'Achievements',

            // Common
            save: 'Save',
            cancel: 'Cancel',
            edit: 'Edit',
            delete: 'Delete',
            confirm: 'Confirm',
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            warning: 'Warning',
            info: 'Info',
            'Add Meal': 'Add Meal',
            'Generate Plan': 'Generate Plan',
            'Сгенерировать план питания': 'Generate Meal Plan',
            generateMealPlan: 'Generate Meal Plan',
            notSpecified: 'Not specified',
            comingSoon: 'Coming Soon',

            // Profile
            personalInfo: 'Personal Information',
            name: 'Name',
            email: 'Email',
            phone: 'Phone',
            address: 'Address',
            bio: 'Bio',
            updateProfile: 'Update Profile',
            profileUpdated: 'Profile updated successfully',
            age: 'Age',
            weight: 'Weight',
            height: 'Height',
            calorieTarget: 'Calorie Target',
            'This field is required': 'This field is required',
            'This field must be a number': 'This field must be a number',
            'Profile updated successfully': 'Profile updated successfully',
            'Error updating profile': 'Error updating profile',
            'Save': 'Save',
            'Edit': 'Edit',
            'Cancel': 'Cancel',
            'First Meal Plan': 'First Meal Plan',
            'Congratulations! You have generated your first meal plan. Keep going!': 'Congratulations! You have generated your first meal plan. Keep going!',
            'Unlocked meal plan customization features': 'Unlocked meal plan customization features',
            'Complete Profile': 'Complete Profile',
            'Fill in all your profile information': 'Fill in all your profile information',
            '5 Meal Plans': '5 Meal Plans',
            'Generate 5 meal plans': 'Generate 5 meal plans',
            'Weight Goal': 'Weight Goal',
            'Reach your target weight': 'Reach your target weight',
            'Congratulations! You have unlocked your first achievement!': 'Congratulations! You have unlocked your first achievement!',
            'Gender': 'Gender',
            'Male': 'Male',
            'Female': 'Female',
            'Other': 'Other',
            'Activity Level': 'Activity Level',
            'Sedentary': 'Sedentary',
            'Light Activity': 'Light Activity',
            'Moderate Activity': 'Moderate Activity',
            'Active': 'Active',
            'Very Active': 'Very Active',
            'Diet Type': 'Diet Type',
            'Balanced': 'Balanced',
            'Vegetarian': 'Vegetarian',
            'Vegan': 'Vegan',
            'Keto': 'Keto',
            'Paleo': 'Paleo',
            'Mediterranean': 'Mediterranean',
            'Low Carb': 'Low Carb',
            'Low Fat': 'Low Fat',
            'Cutting': 'Cutting (Body Drying)',
            'Bulking': 'Bulking (Mass Gain)',
            'Generate Meal': 'Generate Meal',
            'Breakfast': 'Breakfast',
            'Lunch': 'Lunch',
            'Dinner': 'Dinner',
            'Snack': 'Snack',
            'Meal': 'Meal',
            'Nutrition Profile': 'Nutrition Profile',
            'Tell us about yourself to create the perfect meal plan': 'Tell us about yourself to create the perfect meal plan',
            'Basic Information': 'Basic Information',
            'Preferences': 'Preferences',
            'Weight (kg)': 'Weight (kg)',
            'Height (cm)': 'Height (cm)',
            'Daily Calorie Target': 'Daily Calorie Target',
            'Save Profile': 'Save Profile',
            'Age must be between 16 and 100': 'Age must be between 16 and 100',
            'Weight must be between 30 and 300 kg': 'Weight must be between 30 and 300 kg',
            'Height must be between 100 and 250 cm': 'Height must be between 100 and 250 cm',

            // Goals
            goals: 'Goals',
            goalsSection: 'Goals Section',
            setGoals: 'Set Goals',
            weightGoal: 'Weight Goal',
            fitnessGoal: 'Fitness Goal',
            nutritionGoal: 'Nutrition Goal',

            // Meal Plan
            mealPlan: 'Meal Plan',
            mealPlanSection: 'Meal Planning Section',
            generatePlan: 'Generate Plan',
            weeklyPlan: 'Weekly Plan',
            dailyPlan: 'Daily Plan',
            recommendedIntake: 'Recommended Intake',
            actualIntake: 'Actual Intake',

            // Preferences
            preferences: 'Preferences',
            dietaryRestrictions: 'Dietary Restrictions',
            allergies: 'Allergies',
            favoriteCuisines: 'Favorite Cuisines',
            cooking: 'Cooking',
            social: 'Social',

            // Authentication
            loginAction: 'Sign In',
            registerAction: 'Sign Up',
            emailPlaceholder: 'Enter your email',
            passwordPlaceholder: 'Enter your password',
            forgotPassword: 'Forgot Password?',
            rememberMe: 'Remember Me',
            noAccount: "Don't have an account?",
            haveAccount: 'Already have an account?',
            loginTitle: 'Sign In',
            emailLabel: 'Email',
            passwordLabel: 'Password',
            loginButton: 'Sign In',

            // Settings
            accountSettings: 'Account Settings',
            'Account Settings': 'Account Settings',
            userProfile: 'User Profile',
            'Профиль пользователя': 'User Profile',
            security: 'Security',
            'Безопасность': 'Security',
            passwordManagement: 'Password and Security Management',
            'Управление паролем и безопасностью': 'Password and Security Management',
            notificationSettings: 'Notification Settings',
            appearanceSettings: 'Appearance Settings',
            languageSettings: 'Language Settings',
            privacySettings: 'Privacy Settings',
            darkMode: 'Dark Mode',
            notifications: 'Notifications',
            sound: 'Sound',
            emailNotifications: 'Email Notifications',
            twoFactorAuth: 'Two-Factor Authentication',
            dataCollection: 'Data Collection',
            autoSave: 'Auto Save',
            fontSize: 'Font Size',
            themeColor: 'Theme Color',
            timezone: 'Timezone',
            dateFormat: 'Date Format',
            timeFormat: 'Time Format',
            highContrast: 'High Contrast Mode',
            reducedMotion: 'Reduced Motion',
            screenReader: 'Screen Reader Support',
            exportSettings: 'Export Settings',
            importSettings: 'Import Settings',
            resetSettings: 'Reset to Default',
            saveChanges: 'Save Changes',
            changesSaved: 'Changes saved successfully',
            errorSaving: 'Error saving changes',

            // Dashboard
            welcome: 'Welcome',
            todaysMeals: "Today's Meals",
            weeklyProgress: 'Weekly Progress',
            nutritionOverview: 'Nutrition Overview',
            quickStats: 'Quick Stats',
            totalMeals: 'Total Meals',
            todaysCalories: "Today's Calories",
            weeklyGoal: 'Weekly Goal',
            recentActivity: 'Recent Activity',
            mealPlanCreated: 'Meal plan created',
            achievementUnlocked: 'Achievement unlocked',
            profileUpdatedNotification: 'Profile updated',

            // Subscription
            subscriptionPlans: 'Subscription Plans',
            chooseSubscriptionPlan: 'Choose your subscription plan',
            getAccessToPersonalized: 'Get access to personalized meal planning with AI',
            monthlyPlan: 'Monthly Plan',
            quarterlyPlan: '3-Month Plan',
            yearlyPlan: 'Yearly Plan',
            accessToAllFeatures: 'Access to all features for a month',
            mostPopularChoice: 'Most popular choice of our users',
            maximumValueForSerious: 'Maximum value for serious approach',
            freeDays: 'days free',
            mostPopular: 'Most Popular',
            bestPrice: 'Best Price',
            savings: 'savings',
            selectPlan: 'Select Plan',
            currentPlan: 'Current Plan',
            securePayment: 'Secure payment via Stripe',
            cancelAnytime: 'Cancel anytime • 14-day money back guarantee',

            // Subscription features
            aiMealGeneration: 'AI meal plan generation',
            preciseCalorieTracking: 'Precise calorie and macro tracking',
            personalRecommendations: 'Personal recommendations',
            detailedNutritionAnalytics: 'Detailed nutrition analytics',
            allDietTypesSupport: 'Support for all diet types',
            mobileApp: 'Mobile application',
            expandedRecipeDatabase: 'Expanded recipe database',
            prioritySupport: 'Priority support',
            weeklyProgressReports: 'Weekly progress reports',
            fitnessTrackerIntegration: 'Fitness tracker integration',
            nutritionistConsultations: 'Nutritionist consultations',
            personalWorkoutPlans: 'Personal workout plans',
            unlimitedMealPlans: 'Unlimited meal plan generation',
            dataExportReports: 'Data export and reports',
            earlyAccessNewFeatures: 'Early access to new features',

            // Duration and additional features
            month: 'month',
            threeMonths: '3 months',
            year: 'year',
            allMonthlyFeatures: 'All monthly plan features',
            allQuarterlyFeatures: 'All 3-month plan features',
            savingsVsMonthly58: '58% savings compared to monthly',
            savingsVsMonthly83: '83% savings compared to monthly',

            // Subscription benefits
            whatYouGetWithSubscription: 'What you get with subscription',
            aiRecommendations: 'AI Recommendations',
            personalizedMealPlans: 'Personalized meal plans based on your goals and preferences',
            detailedAnalytics: 'Detailed Analytics',
            progressTracking: 'Progress tracking, nutrition analysis and goal achievement',
            unlimitedPlans: 'Unlimited Plans',
            createUnlimitedMealPlans: 'Create unlimited number of meal plans',

            // FAQ
            frequentlyAskedQuestions: 'Frequently Asked Questions',
            canCancelSubscription: 'Can I cancel my subscription?',
            canCancelAnytime: 'Yes, you can cancel your subscription at any time. Access to premium features will remain until the end of the paid period.',
            isRefundAvailable: 'Is there a refund available?',
            fullRefund14Days: 'We offer a full refund within 14 days of purchase if you are not satisfied with the service.',
            isPaymentSecure: 'Is payment secure?',
            stripeSecurePayment: 'Yes, we use Stripe for payment processing - one of the most secure payment services in the world. Your data is protected.',

            // Active subscription
            activeSubscription: 'Active Subscription',
            validUntil: 'Valid until',

            // Account types
            freeAccount: 'Free Account',
            accountType: 'Account Type',
            subscriptionStatus: 'Subscription Status',
            active: 'Active',
            expiringSoon: 'Expiring Soon',
            memberSince: 'Member Since',
            manageSubscription: 'Manage Subscription',
            getPremium: 'Get Premium',
            unknownPlan: 'Unknown Plan',
            basicNutritionFeatures: 'Basic nutrition planning features',

            // Dashboard analytics
            target: 'Target',
            weekly: 'Weekly',
            today: 'Today',
            accuracy: 'Accuracy',
            streak: 'Streak',
            days: 'days',
            ingredients: 'Ingredients',
            protein: 'Protein',
            carbs: 'Carbs',
            fat: 'Fat',
            unlocked: 'Unlocked',
            of: 'of',
            progress: 'Progress',
            thisWeek: 'This week',
            now: 'Now',

            // Achievements
            totalAchievements: 'Total Achievements',
            completed: 'Completed',
            completionRate: 'Completion Rate',
            points: 'Points',
            inProgress: 'In Progress',

            // Achievement categories
            meal_planning: 'Meal Planning',
            nutrition: 'Nutrition',
            consistency: 'Consistency',
            milestones: 'Milestones',
            profile: 'Profile',
            health: 'Health',
            variety: 'Variety',
            social: 'Social',
            loyalty: 'Loyalty',

            // Achievement rarities
            common: 'Common',
            uncommon: 'Uncommon',
            rare: 'Rare',
            epic: 'Epic',
            legendary: 'Legendary',

            // Achievement status
            progress: 'Progress',

            // Achievement titles and descriptions
            firstMealPlan: '🍽️ First Meal Plan',
            firstMealPlanDesc: 'Congratulations! You created your first meal plan. Keep it up!',

            mealPlanMaster: '👨‍🍳 Meal Plan Master',
            mealPlanMasterDesc: 'Created 10 meal plans. You are becoming a real nutrition expert!',

            weeklyStreak: '🔥 Weekly Streak',
            weeklyStreakDesc: 'Maintained your meal plan for 7 days in a row. Consistency is key!',

            monthlyChampion: '🏆 Monthly Champion',
            monthlyChampionDesc: 'Followed your meal plan for 30 days. You are a true champion!',

            calorieTracker: '📊 Calorie Tracker',
            calorieTrackerDesc: 'Tracked calories for 50 meals. Precision is your strength!',

            proteinPower: '💪 Protein Power',
            proteinPowerDesc: 'Consumed optimal protein amounts for 20 days. Your muscles thank you!',

            varietySeeker: '🌈 Variety Seeker',
            varietySeekersDesc: 'Used 50 different ingredients. Diversity in nutrition is important!',

            earlyBird: '🌅 Early Bird',
            earlyBirdDesc: 'Planned breakfast for 30 days. A good day starts with a good breakfast!',

            balancedNutrition: '⚖️ Balanced Nutrition',
            balancedNutritionDesc: 'Achieved perfect macro balance for 15 days. Balance is everything!',

            goalAchiever: '🎯 Goal Achiever',
            goalAchieverDesc: 'Reached your calorie goal 25 times. You know how to set and achieve goals!',

            // Additional achievements
            profileComplete: '👤 Complete Profile',
            profileCompleteDesc: 'Fill in all profile information for better recommendations',
            mealPlans5: '🔥 5 Meal Plans',
            mealPlans5Desc: 'Create 5 different meal plans',
            weightGoal: '🎯 Weight Goal',
            weightGoalDesc: 'Reach your target body weight',
            streak7Days: '📅 Week of Success',
            streak7DaysDesc: 'Follow your meal plan for 7 days in a row',
            calorieMaster: '⚡ Calorie Master',
            calorieMasterDesc: 'Accurately follow your daily calorie target 10 times',
            recipeExplorer: '🌟 Recipe Explorer',
            recipeExplorerDesc: 'Try 20 different recipes',
            socialSharer: '📱 Social Activist',
            socialSharerDesc: 'Share your achievements 5 times',
            healthyChoices: '🥗 Healthy Choices',
            healthyChoicesDesc: 'Choose healthy meals 15 times',
            legendaryUser: '👑 Legendary User',
            legendaryUserDesc: 'Use the app for 30 days in a row',

            // Subscription status
            upgrade: 'Upgrade',
            free: 'Free',

            // Dashboard notifications
            excellentWork: 'Excellent work! You hit the target calorie range',
            addMoreMeals: 'Add more meals - you consumed only',
            ofTarget: 'of target',
            exceedsTarget: 'Exceeds target by',
            watchPortions: '- watch your portions',
            incredibleStreak: 'Incredible! Streak of',
            daysInRow: 'days in a row! You are on the right track!',
            greatStreak: 'Great streak of',
            days: 'days! Keep it up!',
            perfectAccuracy: 'Perfect accuracy',
            masterOfPlanning: 'You are a master of meal planning!',
            excellentAccuracy: 'Excellent accuracy',
            almostPerfect: 'Almost perfect!',
            congratulations: 'Congratulations! Unlocked',
            achievements: 'achievements!',
            excellentVariety: 'Excellent variety! Used',
            uniqueIngredients: 'unique ingredients!',
            welcome: 'Welcome! Create your first meal plan to start tracking',
            greatStart: 'Great start! Add more meals for a complete daily diet',
            amazingWeeklyAccuracy: 'Amazing weekly accuracy',
            youAreProfessional: 'You are a professional!',

            // Analytics
            'Export Data': 'Export Data',
            'Refresh Data': 'Refresh Data',
            'Toggle Predictions': 'Toggle Predictions',
            'No data available for the selected period': 'No data available for the selected period',
            'Try different time range': 'Try different time range',
            'Daily Average': 'Daily Average',
            'Nutrition Details': 'Nutrition Details',
            'Meal Distribution': 'Meal Distribution',
            'Ingredients & Accuracy': 'Ingredients & Accuracy',
            'Trends & Insights': 'Trends & Insights',
            'Nutrition Breakdown by Day': 'Nutrition Breakdown by Day',
            'Macronutrient Distribution': 'Macronutrient Distribution',
            'Calories by Meal Type': 'Calories by Meal Type',
            'Calories by Time of Day': 'Calories by Time of Day',
            'Most Used Ingredients': 'Most Used Ingredients',
            'Target Accuracy Analysis': 'Target Accuracy Analysis',
            'Daily Ingredients Diversity': 'Daily Ingredients Diversity',
            'Unique Ingredients': 'Unique Ingredients',
            'Total Ingredients': 'Total Ingredients',
            'Nutrition Trends': 'Nutrition Trends',
            'Trend': 'Trend',
            'Predictions & Insights': 'Predictions & Insights',
            'Based on your recent consumption patterns, we predict the following trends:': 'Based on your recent consumption patterns, we predict the following trends:',
            'Calorie intake trending upward': 'Calorie intake trending upward',
            'Calorie intake trending downward': 'Calorie intake trending downward',
            'Protein intake increasing': 'Protein intake increasing',
            'Protein intake decreasing': 'Protein intake decreasing',
            'Hide Predictions': 'Hide Predictions',
            'Show Predictions': 'Show Predictions',
            'Filter Analytics': 'Filter Analytics',
            'times': 'times',
            'accuracyExplanation': 'Accuracy shows how close you get to your target KBJU values',
            'fillProfileForAccuracy': 'Fill in your profile to analyze target accuracy',

            // Settings
            emailNotifications: 'Email Notifications',
            emailNotificationsDesc: 'Receive notifications via email',
            pushNotifications: 'Push Notifications',
            pushNotificationsDesc: 'Browser push notifications',
            mealReminders: 'Meal Reminders',
            mealRemindersDesc: 'Reminders about meals',
            achievementAlerts: 'Achievement Alerts',
            achievementAlertsDesc: 'Notifications about achievements',
            appSettings: 'App Settings',
            darkTheme: 'Dark Theme',
            darkThemeDesc: 'Application uses only dark theme',
            language: 'Language',
            languageDesc: 'Choose your preferred language',
            sounds: 'Sounds',
            soundsDesc: 'Enable sound effects',
            animations: 'Animations',
            animationsDesc: 'Enable interface animations',

            // Profile
            basicInformation: 'Basic Information',
            age: 'Age',
            weight: 'Weight (kg)',
            height: 'Height (cm)',
            dailyCalorieTarget: 'Daily Calorie Target',
            preferences: 'Preferences',
            gender: 'Gender',
            activityLevel: 'Activity Level',
            dietType: 'Diet Type',
            male: 'Male',
            female: 'Female',
            other: 'Other',
            light: 'Light',
            moderate: 'Moderate',
            active: 'Active',
            veryActive: 'Very Active',
            vegetarian: 'Vegetarian',
            vegan: 'Vegan',
            keto: 'Keto',
            paleo: 'Paleo',
            mediterranean: 'Mediterranean',
            customKBJU: 'Custom KBJU',
            macronutrients: 'Macronutrients',
            perKgWeight: 'per kg weight',
            ofCalories: 'of calories',

            // Daily Nutrition Summary
            dailyNutritionSummary: 'Daily Nutrition Summary',
            remaining: 'Remaining',
            grams: 'g',
            accurate: 'Accurate',
            deviation: 'Deviation',
            calculation: 'Calculation',
            proteinShort: 'P',
            fatShort: 'F',
            carbsShort: 'C',
            checkKBJUCalculations: 'Check KBJU calculations',

            // Subscription limits
            subscriptionRequired: 'Subscription Required',
            subscriptionRequiredDescription: 'This feature is available only with a premium subscription',
            premiumFeature: 'Premium Feature',
            premiumBenefits: 'Premium Benefits',
            unlimitedAccess: 'Unlimited access to all features',
            upgradeToPremium: 'Upgrade to Premium',
            upgrade: 'Upgrade',
            mealPlanLimitReached: 'Meal Plan Limit Reached',
            upgradeToContinueGenerating: 'Upgrade your subscription to continue generating unlimited meal plans',
            mealPlansUsed: 'Meal Plans Used',
            generationsUsed: 'Generations Used',
            weeklyPlansUsed: 'Weekly Plans Used',
            remainingPlans: 'Remaining Plans',
            remainingGenerations: 'Remaining Generations',
            remainingWeeklyPlans: 'Remaining Weekly Plans',
            weeklyPlanLimitReached: 'Weekly Plan Limit Reached',
            generationLimitReached: 'Generation Limit Reached',
            upgradeToCreateMoreWeeklyPlans: 'Upgrade your subscription to create more weekly meal plans',
            analyticsNotAvailable: 'Analytics Not Available',
            upgradeToAccessAnalytics: 'Upgrade to premium to access detailed analytics and insights',
            achievementsNotAvailable: 'Achievements Not Available',
            upgradeToAccessAchievements: 'Upgrade to premium to unlock achievements and track your progress',
            meals: 'meals',
            noMeals: 'No meals',
            clickPlusToAdd: 'Click + to add',
            Breakfast: 'Breakfast',
            Lunch: 'Lunch',
            Dinner: 'Dinner',
            Snack: 'Snack',
            viewAll: 'View All',
            noMealsToday: 'No meals planned for today',
            addFirstMeal: 'Add your first meal',
            caloriesConsumed: 'Calories consumed',
            proteinIntake: 'Protein intake',
            carbsIntake: 'Carbs intake',
            fatIntake: 'Fat intake',
            dailyGoals: 'Daily Goals',
            weeklyOverview: 'Weekly Overview',
            goodMorning: 'Good Morning',
            goodAfternoon: 'Good Afternoon',
            goodEvening: 'Good Evening',
            user: 'User',
            today: 'Today',
            now: 'Now',
            loadingText: 'Loading...',
            completedStatus: 'Completed',
            'Macronutrients': 'Macronutrients',
            'Protein': 'Protein',
            'Fat': 'Fat',
            'Carbs': 'Carbs',
            'Custom KBJU': 'Custom KBJU',
            'Calories': 'Calories',
            'Detailed Meal Planner': 'Detailed Meal Planner',
            'Enter Target KBJU': 'Enter Target KBJU',
            'Generate Detailed Plan': 'Generate Detailed Plan',
            'Please fill all KBJU fields': 'Please fill all KBJU fields',
            'Meal plan generated successfully!': 'Meal plan generated successfully!',
            'Failed to generate meal plan': 'Failed to generate meal plan',
            'Generated Meal Plan': 'Generated Meal Plan',
            'MealItem': 'Meal',
            'Ingredients': 'Ingredients',
            'Daily Totals': 'Daily Totals',
            'kcal': 'kcal',
            'Create precise meal plans with exact grams': 'Create precise meal plans with exact grams',
            'Target': 'Target',
            'Ingredients & Accuracy': 'Ingredients & Accuracy',
            'Most Used Ingredients': 'Most Used Ingredients',
            'Target Accuracy Analysis': 'Target Accuracy Analysis',
            'Daily Ingredients Diversity': 'Daily Ingredients Diversity',
            'Unique Ingredients': 'Unique Ingredients',
            'Total Ingredients': 'Total Ingredients',
            'Today Protein': 'Today Protein',
            'Accuracy Score': 'Accuracy Score',
            'Target accuracy': 'Target accuracy',
            'Ingredients diversity': 'Ingredients diversity',
            'CarbsNutrient': 'Carbs',
            'FatNutrient': 'Fat',

            // Achievements
            achievements: 'Achievements',
            totalAchievements: 'Total Achievements',
            completedAchievements: 'Completed',
            completionRate: 'Completion Rate',
            achievementCompleted: 'Completed',
            inProgress: 'In Progress',
            allCategories: 'All Categories',
            beginner: 'Beginner',
            consistency: 'Consistency',
            nutrition: 'Nutrition',
            health: 'Health',
            control: 'Control',
            mastery: 'Mastery',
            lifestyle: 'Lifestyle',
            firstMealPlan: 'First Meal Plan',
            firstMealPlanDesc: 'Create your first meal plan',
            firstMeal: 'First Meal',
            firstMealDesc: 'Add your first meal to the plan',
            regularMeals: 'Regular Meals',
            regularMealsDesc: 'Eat 3 meals a day for 7 days',
            mealVariety: 'Meal Variety',
            mealVarietyDesc: 'Try 10 different dishes in a week',
            balancedNutrition: 'Balanced Nutrition',
            balancedNutritionDesc: 'Follow the balance of BCA in 5 days',
            healthySnacks: 'Healthy Snacks',
            healthySnacksDesc: 'Make 5 healthy snacks (less than 200 calories)',
            calorieControl: 'Calorie Control',
            calorieControlDesc: 'Follow the calorie norm in 5 days',
            monthlyStreak: 'Monthly Streak',
            monthlyStreakDesc: 'Plan your meals for 30 days in a row',
            mealMaster: 'Meal Master',
            mealMasterDesc: 'Try 50 different dishes',
            perfectBalance: 'Perfect Balance',
            perfectBalanceDesc: 'Follow the perfect balance of BCA (30/40/30) for 3 days',
            caloriePerfection: 'Calorie Perfection',
            caloriePerfectionDesc: 'Follow the calorie norm with an accuracy of 50 calories for 3 days',
            earlyBird: 'Early Bird',
            earlyBirdDesc: 'Eat between 6-9 AM 5 days',
            nightOwl: 'Night Owl',
            nightOwlDesc: 'Eat between 18-21 PM 5 days',
            reward: 'Reward'
        },
        ru: {
            // Navigation
            home: 'Главная',
            dashboard: 'Панель управления',
            'Dashboard': 'Панель управления',
            'Meal Plan': 'План питания',
            'Analytics': 'Аналитика',
            'Achievements': 'Достижения',
            'Profile': 'Профиль',
            profile: 'Профиль',
            settings: 'Настройки',
            'Subscription': 'Подписка',
            logout: 'Выйти',
            login: 'Войти',
            register: 'Регистрация',

            // Tab Bar Navigation
            mealPlan: 'План питания',
            analytics: 'Аналитика',
            achievements: 'Достижения',

            // Common
            save: 'Сохранить',
            cancel: 'Отмена',
            edit: 'Редактировать',
            delete: 'Удалить',
            confirm: 'Подтвердить',
            loading: 'Загрузка...',
            error: 'Ошибка',
            success: 'Успешно',
            warning: 'Предупреждение',
            info: 'Информация',
            'Add Meal': 'Добавить блюдо',
            'Generate Plan': 'Сгенерировать план',
            'Сгенерировать план питания': 'Сгенерировать план питания',
            generateMealPlan: 'Сгенерировать план питания',
            notSpecified: 'Не указан',
            comingSoon: 'Скоро',

            // Profile
            personalInfo: 'Личная информация',
            name: 'Имя',
            email: 'Email',
            phone: 'Телефон',
            address: 'Адрес',
            bio: 'О себе',
            updateProfile: 'Обновить профиль',
            profileUpdated: 'Профиль успешно обновлен',
            age: 'Возраст',
            weight: 'Вес',
            height: 'Рост',
            calorieTarget: 'Целевые калории',
            'This field is required': 'Это поле обязательно',
            'This field must be a number': 'Это поле должно быть числом',
            'Profile updated successfully': 'Профиль успешно обновлен',
            'Error updating profile': 'Ошибка обновления профиля',
            'Profile': 'Профиль',
            'Save': 'Сохранить',
            'Edit': 'Редактировать',
            'Cancel': 'Отмена',
            'First Meal Plan': 'Первый план питания',
            'Congratulations! You have generated your first meal plan. Keep going!': 'Поздравляем! Вы создали свой первый план питания. Продолжайте!',
            'Unlocked meal plan customization features': 'Открыты функции настройки плана питания',
            'Complete Profile': 'Заполнить профиль',
            'Fill in all your profile information': 'Заполните всю информацию профиля',
            '5 Meal Plans': '5 планов питания',
            'Generate 5 meal plans': 'Создать 5 планов питания',
            'Weight Goal': 'Цель по весу',
            'Reach your target weight': 'Достичь целевого веса',
            'Congratulations! You have unlocked your first achievement!': 'Поздравляем! Вы открыли свое первое достижение!',
            'Gender': 'Пол',
            'Male': 'Мужской',
            'Female': 'Женский',
            'Other': 'Другой',
            'Activity Level': 'Уровень активности',
            'Sedentary': 'Малоподвижный',
            'Light Activity': 'Легкая активность',
            'Moderate Activity': 'Умеренная активность',
            'Active': 'Активный',
            'Very Active': 'Очень активный',
            'Diet Type': 'Тип диеты',
            'Balanced': 'Сбалансированная',
            'Vegetarian': 'Вегетарианская',
            'Vegan': 'Веганская',
            'Keto': 'Кето',
            'Paleo': 'Палео',
            'Mediterranean': 'Средиземноморская',
            'Low Carb': 'Низкоуглеводная',
            'Low Fat': 'Низкожирная',
            'Cutting': 'Сушка тела',
            'Bulking': 'Массонабор',
            'Generate Meal': 'Сгенерировать блюдо',
            'Breakfast': 'Завтрак',
            'Lunch': 'Обед',
            'Dinner': 'Ужин',
            'Snack': 'Перекус',
            'Meal': 'Блюдо',
            'Nutrition Profile': 'Профиль питания',
            'Tell us about yourself to create the perfect meal plan': 'Расскажите о себе, чтобы создать идеальный план питания',
            'Basic Information': 'Основная информация',
            'Preferences': 'Предпочтения',
            'Weight (kg)': 'Вес (кг)',
            'Height (cm)': 'Рост (см)',
            'Daily Calorie Target': 'Дневная норма калорий',
            'Save Profile': 'Сохранить профиль',
            'Age must be between 16 and 100': 'Возраст должен быть от 16 до 100 лет',
            'Weight must be between 30 and 300 kg': 'Вес должен быть от 30 до 300 кг',
            'Height must be between 100 and 250 cm': 'Рост должен быть от 100 до 250 см',

            // Goals
            goals: 'Цели',
            goalsSection: 'Раздел целей',
            setGoals: 'Установить цели',
            weightGoal: 'Цель по весу',
            fitnessGoal: 'Фитнес цель',
            nutritionGoal: 'Цель по питанию',

            // Meal Plan
            mealPlan: 'План питания',
            mealPlanSection: 'Раздел планирования питания',
            generatePlan: 'Сгенерировать план',
            weeklyPlan: 'Недельный план',
            dailyPlan: 'Ежедневный план',
            recommendedIntake: 'Рекомендуемое потребление',
            actualIntake: 'Фактическое потребление',

            // Preferences
            preferences: 'Предпочтения',
            dietaryRestrictions: 'Диетические ограничения',
            allergies: 'Аллергии',
            favoriteCuisines: 'Любимые кухни',
            cooking: 'Готовка',
            social: 'Социальное',

            // Authentication
            loginAction: 'Войти в систему',
            registerAction: 'Зарегистрироваться',
            emailPlaceholder: 'Введите email',
            passwordPlaceholder: 'Введите пароль',
            forgotPassword: 'Забыли пароль?',
            rememberMe: 'Запомнить меня',
            noAccount: 'Нет аккаунта?',
            haveAccount: 'Уже есть аккаунт?',
            loginTitle: 'Вход в систему',
            emailLabel: 'Email',
            passwordLabel: 'Пароль',
            loginButton: 'Войти',

            // Settings
            accountSettings: 'Настройки аккаунта',
            'Account Settings': 'Настройки аккаунта',
            userProfile: 'Профиль пользователя',
            'Профиль пользователя': 'Профиль пользователя',
            security: 'Безопасность',
            'Безопасность': 'Безопасность',
            passwordManagement: 'Управление паролем и безопасностью',
            'Управление паролем и безопасностью': 'Управление паролем и безопасностью',
            notificationSettings: 'Настройки уведомлений',
            appearanceSettings: 'Настройки внешнего вида',
            languageSettings: 'Настройки языка',
            privacySettings: 'Настройки конфиденциальности',
            darkMode: 'Темная тема',
            notifications: 'Уведомления',
            sound: 'Звук',
            emailNotifications: 'Email уведомления',
            twoFactorAuth: 'Двухфакторная аутентификация',
            dataCollection: 'Сбор данных',
            autoSave: 'Автосохранение',
            fontSize: 'Размер шрифта',
            themeColor: 'Цвет темы',
            timezone: 'Часовой пояс',
            dateFormat: 'Формат даты',
            timeFormat: 'Формат времени',
            highContrast: 'Высокая контрастность',
            reducedMotion: 'Уменьшенная анимация',
            screenReader: 'Поддержка экранного диктора',
            exportSettings: 'Экспорт настроек',
            importSettings: 'Импорт настроек',
            resetSettings: 'Сбросить настройки',
            saveChanges: 'Сохранить изменения',
            changesSaved: 'Изменения успешно сохранены',
            errorSaving: 'Ошибка при сохранении',

            // Dashboard
            welcome: 'Добро пожаловать',
            todaysMeals: 'Сегодняшние блюда',
            weeklyProgress: 'Недельный прогресс',
            nutritionOverview: 'Обзор питания',
            quickStats: 'Быстрая статистика',
            totalMeals: 'Всего блюд',
            todaysCalories: 'Калории сегодня',
            weeklyGoal: 'Недельная цель',
            recentActivity: 'Недавняя активность',
            mealPlanCreated: 'План питания создан',
            achievementUnlocked: 'Достижение разблокировано',
            profileUpdatedNotification: 'Профиль обновлен',

            // Subscription
            subscriptionPlans: 'Планы подписки',
            chooseSubscriptionPlan: 'Выберите план подписки',
            getAccessToPersonalized: 'Получите доступ к персонализированному планированию питания с помощью ИИ',
            monthlyPlan: 'Месячный план',
            quarterlyPlan: 'Трёхмесячный план',
            yearlyPlan: 'Годовой план',
            accessToAllFeatures: 'Доступ ко всем функциям на месяц',
            mostPopularChoice: 'Самый популярный выбор наших пользователей',
            maximumValueForSerious: 'Максимальная выгода для серьезного подхода',
            freeDays: 'дня бесплатно',
            mostPopular: 'Самый популярный',
            bestPrice: 'Лучшая цена',
            savings: 'экономия',
            selectPlan: 'Выбрать план',
            currentPlan: 'Текущий план',
            securePayment: 'Безопасная оплата через Stripe',
            cancelAnytime: 'Отмена подписки в любое время • Возврат средств в течение 14 дней',

            // Subscription features
            aiMealGeneration: 'Генерация планов питания с ИИ',
            preciseCalorieTracking: 'Точный подсчет калорий и КБЖУ',
            personalRecommendations: 'Персональные рекомендации',
            detailedNutritionAnalytics: 'Детальная аналитика питания',
            allDietTypesSupport: 'Поддержка всех типов диет',
            mobileApp: 'Мобильное приложение',
            expandedRecipeDatabase: 'Расширенная база рецептов',
            prioritySupport: 'Приоритетная поддержка',
            weeklyProgressReports: 'Еженедельные отчеты прогресса',
            fitnessTrackerIntegration: 'Интеграция с фитнес-трекерами',
            nutritionistConsultations: 'Консультации с нутрициологом',
            personalWorkoutPlans: 'Индивидуальные планы тренировок',
            unlimitedMealPlans: 'Безлимитная генерация планов',
            dataExportReports: 'Экспорт данных и отчетов',
            earlyAccessNewFeatures: 'Ранний доступ к новым функциям',

            // Duration and additional features
            month: 'месяц',
            threeMonths: '3 месяца',
            year: 'год',
            allMonthlyFeatures: 'Все функции месячного плана',
            allQuarterlyFeatures: 'Все функции трёхмесячного плана',
            savingsVsMonthly58: 'Экономия 58% по сравнению с месячным',
            savingsVsMonthly83: 'Экономия 83% по сравнению с месячным',

            // Subscription benefits
            whatYouGetWithSubscription: 'Что вы получите с подпиской',
            aiRecommendations: 'ИИ-рекомендации',
            personalizedMealPlans: 'Персонализированные планы питания на основе ваших целей и предпочтений',
            detailedAnalytics: 'Детальная аналитика',
            progressTracking: 'Отслеживание прогресса, анализ питания и достижение целей',
            unlimitedPlans: 'Безлимитные планы',
            createUnlimitedMealPlans: 'Создавайте неограниченное количество планов питания',

            // FAQ
            frequentlyAskedQuestions: 'Часто задаваемые вопросы',
            canCancelSubscription: 'Можно ли отменить подписку?',
            canCancelAnytime: 'Да, вы можете отменить подписку в любое время. Доступ к премиум-функциям сохранится до конца оплаченного периода.',
            isRefundAvailable: 'Есть ли возврат средств?',
            fullRefund14Days: 'Мы предлагаем полный возврат средств в течение 14 дней с момента покупки, если вы не удовлетворены сервисом.',
            isPaymentSecure: 'Безопасна ли оплата?',
            stripeSecurePayment: 'Да, мы используем Stripe для обработки платежей - один из самых безопасных платежных сервисов в мире. Ваши данные защищены.',

            // Active subscription
            activeSubscription: 'Активная подписка',
            validUntil: 'Действует до',

            // Account types
            freeAccount: 'Бесплатный аккаунт',
            accountType: 'Тип аккаунта',
            subscriptionStatus: 'Статус подписки',
            active: 'Активна',
            expiringSoon: 'Истекает скоро',
            memberSince: 'Участник с',
            manageSubscription: 'Управление подпиской',
            getPremium: 'Получить премиум',
            unknownPlan: 'Неизвестный план',
            basicNutritionFeatures: 'Базовые возможности планирования питания',

            // Dashboard analytics
            target: 'Цель',
            weekly: 'Недельно',
            today: 'Сегодня',
            accuracy: 'Точность',
            streak: 'Стрик',
            days: 'дней',
            ingredients: 'Ингредиенты',
            protein: 'Белки',
            carbs: 'Углеводы',
            fat: 'Жиры',
            unlocked: 'Разблокировано',
            of: 'из',
            progress: 'Прогресс',
            thisWeek: 'На этой неделе',
            now: 'Сейчас',
            viewAll: 'Посмотреть все',
            noMealsToday: 'На сегодня блюда не запланированы',
            addFirstMeal: 'Добавьте первое блюдо',
            caloriesConsumed: 'Потреблено калорий',
            proteinIntake: 'Потребление белков',
            carbsIntake: 'Потребление углеводов',
            fatIntake: 'Потребление жиров',
            dailyGoals: 'Дневные цели',
            weeklyOverview: 'Недельный обзор',
            goodMorning: 'Доброе утро',
            goodAfternoon: 'Добрый день',
            goodEvening: 'Добрый вечер',
            user: 'Пользователь',
            today: 'Сегодня',
            now: 'Сейчас',
            loadingText: 'Загрузка...',
            completedStatus: 'Завершено',
            'Macronutrients': 'Макронутриенты',
            'Protein': 'Белки',
            'Fat': 'Жиры',
            'Carbs': 'Углеводы',
            'Custom KBJU': 'Ручной ввод КБЖУ',
            'Calories': 'Калории',
            'Detailed Meal Planner': 'Детальный планировщик питания',
            'Enter Target KBJU': 'Введите целевые КБЖУ',
            'Generate Detailed Plan': 'Создать детальный план',
            'Please fill all KBJU fields': 'Пожалуйста, заполните все поля КБЖУ',
            'Meal plan generated successfully!': 'План питания успешно создан!',
            'Failed to generate meal plan': 'Не удалось создать план питания',
            'Generated Meal Plan': 'Сгенерированный план питания',
            'MealItem': 'Блюдо',
            'Ingredients': 'Ингредиенты',
            'Daily Totals': 'Итоги дня',
            'kcal': 'ккал',
            'Create precise meal plans with exact grams': 'Создавайте точные планы питания с указанием граммов',
            'Target': 'Цель',
            'Ingredients & Accuracy': 'Ингредиенты и точность',
            'Most Used Ingredients': 'Самые используемые ингредиенты',
            'Target Accuracy Analysis': 'Анализ точности попадания в цель',
            'Daily Ingredients Diversity': 'Разнообразие ингредиентов по дням',
            'Unique Ingredients': 'Уникальные ингредиенты',
            'Total Ingredients': 'Всего ингредиентов',
            'Today Protein': 'Белки сегодня',
            'Accuracy Score': 'Точность попадания',
            'Target accuracy': 'Точность цели',
            'Ingredients diversity': 'Разнообразие ингредиентов',
            'CarbsNutrient': 'Углеводы',
            'FatNutrient': 'Жиры',

            // Achievements
            achievements: 'Достижения',
            totalAchievements: 'Всего достижений',
            completedAchievements: 'Завершено',
            completionRate: 'Процент выполнения',
            achievementCompleted: 'Завершено',
            inProgress: 'В процессе',
            allCategories: 'Все категории',
            beginner: 'Начинающий',
            consistency: 'Последовательность',
            nutrition: 'Питание',
            health: 'Здоровье',
            control: 'Контроль',
            mastery: 'Мастерство',
            lifestyle: 'Образ жизни',
            firstMealPlan: 'Первый план питания',
            firstMealPlanDesc: 'Создайте свой первый план питания',
            firstMeal: 'Первая еда',
            firstMealDesc: 'Добавьте первую еду в план',
            regularMeals: 'Регулярное питание',
            regularMealsDesc: 'Питайтесь 3 раза в день в течение 7 дней',
            mealVariety: 'Разнообразие блюд',
            mealVarietyDesc: 'Попробуйте 10 разных блюд за неделю',
            balancedNutrition: 'Сбалансированное питание',
            balancedNutritionDesc: 'Соблюдайте баланс БЖУ в течение 5 дней',
            healthySnacks: 'Здоровые перекусы',
            healthySnacksDesc: 'Сделайте 5 здоровых перекусов (менее 200 калорий)',
            calorieControl: 'Контроль калорий',
            calorieControlDesc: 'Соблюдайте норму калорий в течение 5 дней',
            monthlyStreak: 'Месячная последовательность',
            monthlyStreakDesc: 'Планируйте питание 30 дней подряд',
            mealMaster: 'Мастер блюд',
            mealMasterDesc: 'Попробуйте 50 разных блюд',
            perfectBalance: 'Идеальный баланс',
            perfectBalanceDesc: 'Соблюдайте идеальное соотношение БЖУ (30/40/30) 3 дня',
            caloriePerfection: 'Идеальный контроль калорий',
            caloriePerfectionDesc: 'Соблюдайте норму калорий с точностью до 50 калорий 3 дня',
            earlyBird: 'Ранняя пташка',
            earlyBirdDesc: 'Завтракайте между 6-9 утра 5 дней',
            nightOwl: 'Ночная сова',
            nightOwlDesc: 'Ужинайте между 18-21 вечера 5 дней',
            reward: 'Награда',

            // Additional achievement translations
            mealPlanMaster: '👨‍🍳 Мастер планирования',
            mealPlanMasterDesc: 'Создано 10 планов питания. Вы становитесь настоящим экспертом по питанию!',

            weeklyStreak: '🔥 Недельная серия',
            weeklyStreakDesc: 'Соблюдали план питания 7 дней подряд. Постоянство - это ключ!',

            monthlyChampion: '🏆 Чемпион месяца',
            monthlyChampionDesc: 'Следовали плану питания 30 дней. Вы настоящий чемпион!',

            calorieTracker: '📊 Счетчик калорий',
            calorieTrackerDesc: 'Отслеживали калории в 50 блюдах. Точность - ваша сила!',

            proteinPower: '💪 Белковая сила',
            proteinPowerDesc: 'Потребляли оптимальное количество белка 20 дней. Ваши мышцы благодарят вас!',

            varietySeeker: '🌈 Искатель разнообразия',
            varietySeekersDesc: 'Использовали 50 различных ингредиентов. Разнообразие в питании важно!',

            goalAchiever: '🎯 Достигатель целей',
            goalAchieverDesc: 'Достигли цели по калориям 25 раз. Вы умеете ставить и достигать цели!',

            // Additional achievements
            profileComplete: '👤 Полный профиль',
            profileCompleteDesc: 'Заполните всю информацию в профиле для лучших рекомендаций',
            mealPlans5: '🔥 5 планов питания',
            mealPlans5Desc: 'Создайте 5 различных планов питания',
            weightGoal: '🎯 Цель по весу',
            weightGoalDesc: 'Достигните своей целевой массы тела',
            streak7Days: '📅 Неделя успеха',
            streak7DaysDesc: 'Следуйте плану питания 7 дней подряд',
            calorieMaster: '⚡ Мастер калорий',
            calorieMasterDesc: 'Точно соблюдайте дневную норму калорий 10 раз',
            recipeExplorer: '🌟 Исследователь рецептов',
            recipeExplorerDesc: 'Попробуйте 20 различных рецептов',
            socialSharer: '📱 Социальный активист',
            socialSharerDesc: 'Поделитесь своими успехами 5 раз',
            healthyChoices: '🥗 Здоровый выбор',
            healthyChoicesDesc: 'Выберите здоровые блюда 15 раз',
            legendaryUser: '👑 Легендарный пользователь',
            legendaryUserDesc: 'Используйте приложение 30 дней подряд',

            // Subscription status
            upgrade: 'Обновить',
            free: 'Бесплатно',

            // Dashboard notifications
            excellentWork: 'Отличная работа! Вы попали в целевой диапазон калорий',
            addMoreMeals: 'Добавьте больше блюд - вы потребили только',
            ofTarget: 'от цели',
            exceedsTarget: 'Превышение цели на',
            watchPortions: '- следите за порциями',
            incredibleStreak: 'Невероятно! Стрик',
            daysInRow: 'дней подряд! Вы на правильном пути!',
            greatStreak: 'Отличный стрик',
            days: 'дня! Продолжайте в том же духе!',
            perfectAccuracy: 'Идеальная точность',
            masterOfPlanning: 'Вы мастер планирования питания!',
            excellentAccuracy: 'Отличная точность',
            almostPerfect: 'Почти идеально!',
            congratulations: 'Поздравляем! Разблокировано',
            achievements: 'достижений!',
            excellentVariety: 'Отличное разнообразие! Использовано',
            uniqueIngredients: 'уникальных ингредиентов!',
            welcome: 'Добро пожаловать! Создайте свой первый план питания для начала отслеживания',
            greatStart: 'Отличное начало! Добавьте еще блюд для полного дневного рациона',
            amazingWeeklyAccuracy: 'Потрясающая недельная точность',
            youAreProfessional: 'Вы профессионал!',

            // Analytics
            'Export Data': 'Экспорт данных',
            'Refresh Data': 'Обновить данные',
            'Toggle Predictions': 'Переключить прогнозы',
            'No data available for the selected period': 'Нет данных за выбранный период',
            'Try different time range': 'Попробуйте другой временной диапазон',
            'Daily Average': 'Среднее за день',
            'Nutrition Details': 'Детали питания',
            'Meal Distribution': 'Распределение приемов пищи',
            'Ingredients & Accuracy': 'Ингредиенты и точность',
            'Trends & Insights': 'Тренды и аналитика',
            'Nutrition Breakdown by Day': 'Разбивка питания по дням',
            'Macronutrient Distribution': 'Распределение макронутриентов',
            'Calories by Meal Type': 'Калории по типу приема пищи',
            'Calories by Time of Day': 'Калории по времени дня',
            'Most Used Ingredients': 'Наиболее используемые ингредиенты',
            'Target Accuracy Analysis': 'Анализ точности попадания в цели',
            'Daily Ingredients Diversity': 'Ежедневное разнообразие ингредиентов',
            'Unique Ingredients': 'Уникальные ингредиенты',
            'Total Ingredients': 'Всего ингредиентов',
            'Nutrition Trends': 'Тренды питания',
            'Trend': 'Тренд',
            'Predictions & Insights': 'Прогнозы и аналитика',
            'Based on your recent consumption patterns, we predict the following trends:': 'На основе ваших недавних паттернов потребления мы прогнозируем следующие тренды:',
            'Calorie intake trending upward': 'Потребление калорий растет',
            'Calorie intake trending downward': 'Потребление калорий снижается',
            'Protein intake increasing': 'Потребление белка увеличивается',
            'Protein intake decreasing': 'Потребление белка снижается',
            'Hide Predictions': 'Скрыть прогнозы',
            'Show Predictions': 'Показать прогнозы',
            'Filter Analytics': 'Фильтр аналитики',
            'times': 'раз',
            'accuracyExplanation': 'Точность показывает, насколько близко вы попадаете в целевые значения КБЖУ',
            'fillProfileForAccuracy': 'Заполните профиль для анализа точности попадания в цели',

            // Settings
            emailNotifications: 'Email уведомления',
            emailNotificationsDesc: 'Получать уведомления на email',
            pushNotifications: 'Push уведомления',
            pushNotificationsDesc: 'Push уведомления в браузере',
            mealReminders: 'Напоминания о приемах пищи',
            mealRemindersDesc: 'Напоминания о приемах пищи',
            achievementAlerts: 'Уведомления о достижениях',
            achievementAlertsDesc: 'Уведомления о достижениях',
            appSettings: 'Настройки приложения',
            darkTheme: 'Темная тема',
            darkThemeDesc: 'Приложение использует только темную тему',
            language: 'Язык',
            languageDesc: 'Выберите предпочитаемый язык',
            sounds: 'Звуки',
            soundsDesc: 'Включить звуковые эффекты',
            animations: 'Анимации',
            animationsDesc: 'Включить анимации интерфейса',

            // Profile
            basicInformation: 'Основная информация',
            age: 'Возраст',
            weight: 'Вес (кг)',
            height: 'Рост (см)',
            dailyCalorieTarget: 'Дневная цель калорий',
            preferences: 'Предпочтения',
            gender: 'Пол',
            activityLevel: 'Уровень активности',
            dietType: 'Тип диеты',
            male: 'Мужской',
            female: 'Женский',
            other: 'Другой',
            light: 'Легкий',
            moderate: 'Умеренный',
            active: 'Активный',
            veryActive: 'Очень активный',
            vegetarian: 'Вегетарианская',
            vegan: 'Веганская',
            keto: 'Кето',
            paleo: 'Палео',
            mediterranean: 'Средиземноморская',
            customKBJU: 'Пользовательские КБЖУ',
            macronutrients: 'Макронутриенты',
            perKgWeight: 'на кг веса',
            ofCalories: 'калорий',

            // Daily Nutrition Summary
            dailyNutritionSummary: 'Дневная сводка питания',
            remaining: 'Осталось',
            grams: 'г',
            accurate: 'Точно',
            deviation: 'Отклонение',
            calculation: 'Расчет',
            proteinShort: 'Б',
            fatShort: 'Ж',
            carbsShort: 'У',
            checkKBJUCalculations: 'Проверьте расчеты КБЖУ',

            // Subscription limits
            subscriptionRequired: 'Требуется подписка',
            subscriptionRequiredDescription: 'Эта функция доступна только с премиум подпиской',
            premiumFeature: 'Премиум функция',
            premiumBenefits: 'Преимущества премиум',
            unlimitedAccess: 'Безлимитный доступ ко всем функциям',
            upgradeToPremium: 'Обновить до премиум',
            upgrade: 'Обновить',
            mealPlanLimitReached: 'Достигнут лимит планов питания',
            upgradeToContinueGenerating: 'Обновите подписку для продолжения генерации безлимитных планов питания',
            mealPlansUsed: 'Использовано планов питания',
            generationsUsed: 'Использовано генераций',
            weeklyPlansUsed: 'Использовано недельных планов',
            remainingPlans: 'Осталось планов',
            remainingGenerations: 'Осталось генераций',
            remainingWeeklyPlans: 'Осталось недельных планов',
            weeklyPlanLimitReached: 'Достигнут лимит недельных планов',
            generationLimitReached: 'Достигнут лимит генераций',
            upgradeToCreateMoreWeeklyPlans: 'Обновите подписку для создания большего количества недельных планов питания',
            analyticsNotAvailable: 'Аналитика недоступна',
            upgradeToAccessAnalytics: 'Обновите до премиум для доступа к детальной аналитике и инсайтам',
            achievementsNotAvailable: 'Достижения недоступны',
            upgradeToAccessAchievements: 'Обновите до премиум для разблокировки достижений и отслеживания прогресса',
            meals: 'блюд',
            noMeals: 'Нет блюд',
            clickPlusToAdd: 'Нажмите + чтобы добавить',
            Breakfast: 'Завтрак',
            Lunch: 'Обед',
            Dinner: 'Ужин',
            Snack: 'Перекус',

            // Achievement categories
            meal_planning: 'Планирование питания',
            nutrition: 'Питание',
            consistency: 'Постоянство',
            milestones: 'Вехи',
            profile: 'Профиль',
            health: 'Здоровье',
            variety: 'Разнообразие',
            social: 'Социальное',
            loyalty: 'Лояльность',
            points: 'Очки',

            // Achievement rarities
            common: 'Обычное',
            uncommon: 'Необычное',
            rare: 'Редкое',
            epic: 'Эпическое',
            legendary: 'Легендарное',

            // Achievement status
            progress: 'Прогресс',
        }
    });

    const switchLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    useEffect(() => {
        const savedLanguage = localStorage.getItem('language');
        if (savedLanguage) {
            setLanguage(savedLanguage);
        }
    }, []);

    const t = (key) => {
        return translations[language]?.[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, switchLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

LanguageProvider.propTypes = {
    children: PropTypes.node.isRequired
};